apiVersion: v1
kind: Namespace
metadata:
  name: one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: one
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 15
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.666
