apiVersion: v1
kind: Pod
metadata:
  name: sega
spec:
  containers:
  - name: busy01
    image: busybox
    args: ["/bin/sh", "-c", "echo 'hello'; sleep 3600"]
  - name: busy02
    image: busybox
    args: ["/bin/sh", "-c", "echo 'hello'; sleep 3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
spec:
  initContainers:
  - name: init
    image: busybox
    command: ["wget -O /work-dir/index.html http://kubernetes.io"]
    volumeMounts: 
    - mountPath: /work-dir
      name: em-vol
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts: 
    - mountPath: /usr/share/nginx/html
      name: em-vol
  volumes:
  - name: em-vol
    emptyDir: {}
