apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: NjU0MzIx
  MYSQL_USER: bWVoZGk=
  MYSQL_PASSWORD: NjU0MzIx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      name: mysql
      labels: 
        app: mysqldb 
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          envFrom:
          - secretRef:
              name: mysecret
