apiVersion: v1
kind: Pod
metadata:
  name: nginx-448839
spec:
  containers:
  - name: nginx
    image: nginx:alpine
---
apiVersion: v1
kind: Namespace
metadata:
  name: apx-z993845
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend 
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4-alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: messaging
  labels:
    tier: msg
spec:
  containers:
  - name: redis
    image: redis:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: marketing
spec:
  selector:
    name: redis-pod
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-3392845
data:
  DB_NAME: "SQL3322"
  DB_HOST: "sql322.mycompany.com"
  DB_PORT: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret-xxdf
data:
  DB_User: "LWkgcm9vdAo="
  DB_Host: "LWkgc3FsMDEK"
  DB_Password: "LWkgcGFzc3dvcmQxMjMK"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pv/data-analytics
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-access
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: redis
    ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: sega
spec:
  containers:
  - name: tails
    image: busybox
    command: ["sleep" ,"3600"]
  - name: sonic
    image: nginx
    env:
    - name: NGINX_PORT
      value: "8080"








