apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  labels: 
    pv: wordpress
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /html
    server: nfs01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels: 
    pv: mysql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mysql
    server: nfs01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        volumeMounts: 
          - mountPath: "/var/lib/mysql"
            name: mysql-persistent-storage
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mysql-pass
                key: password
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-stuff
  template:
    metadata:
      labels:
        app: wordpress-stuff
    spec:
      containers:
      - name: wordpress
        image: wordpress
        volumeMounts: 
          - mountPath: "/var/www/html"
            name: wordpress-persistent-storage
        env:
          - name: WORDPRESS_DB_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mysql-pass
                key: password
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress-stuff
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31004

