---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels: 
    pv: data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: data-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: gop-fileserver
spec:
  containers:
  - name: fileserver
    image: kodekloud/fileserver
    volumeMounts: 
    - mountPath: "/web"
      name: data-store
  volumes:
  - name: data-store
    persistentVolumeClaim:
        claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    app: gop-fileserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
